
import type { Metadata } from "next";
import { Inter } from "next/font/google";
 import "./globals.css"
import { MobileSidebar } from "./(landing)/_components/mobile-sidebar";
import { cn } from "@/lib/utils";
import localFont from "next/font/local";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const headingFont = localFont({
  src:"./Honk.ttf",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex text-4xl flex-grow bg-gray-800 text-white p-4 gap-14">
     
      <div className="z-50"><MobileSidebar /></div>
      <div className={cn("", headingFont.className)}>Animystics</div>
    </div>
        {children}</body>
    </html>
  )
}
